/* scope.h */

#ifndef _SCOPE_H_
#define _SCOPE_H_

#include "pair.h"
#include "hashMap.h"

typedef struct Func Func;
typedef struct Variable Variable;
typedef struct Object Template;

typedef struct Scope {
    /* Template is generated by object
     * declaration, new object will be
     * generated by copy from a specific
     * template.
     *
     * Map<type::String, O::Object>*/
    hashMap *template;
    /* Map<ident, function> */
    hashMap *functions;
    /* Map<ident, Variable> */
    hashMap *primitives;
    /* Map<ident, Template> */
    hashMap *objects;

    /* Reference to outer scope */
    struct Scope *outer;
} Scope;

#define isFuncExists(s, f) (scopeGetFunc(s,f) != null)
#define isPrimitiveExists(s, p) (scopeGetPrimitive(s, p) != null)
#define isObjectExists(s, o) (scopeGetObject(s, o) != null)
#define isTemplateExists(s, t) (scopeGetTemplate(s, t) != NULL)

/* Prototypes */
Scope * scopeGenerate();
Scope * subScopeGenerate(Scope *);
void scopeRelease(Scope *);
void scopeReleaseCurrent(Scope *);

Func * scopeGetFunc(Scope *, char *);
Variable * scopeGetPrimitive(Scope *, char *);
Variable * scopeGetObject(Scope *, char *);
Template * scopeGetTemplate(Scope *, char *);

_Bool scopeIsValidType(char *type, Scope *);

/* pair<identifier, Func> */
_Status_t scopeNewFunc(Scope *, pair *);
/* pair<identifier, Variable> */
_Status_t scopeNewPrimitive(Scope *, pair *);
/* pair<identifier, Variable> */
_Status_t scopeNewObject(Scope *, pair *);
/* pair<identifier, Template> */
_Status_t scopeNewTemplate(Scope *, pair *);

#ifdef _AST_TREE_TESTING_

void scopeTest(void **state);

#endif /* _AST_TREE_TESTING_ */

#endif /* _SCOPE_H_ */
