/* scope.h */

#ifndef _SCOPE_H_
#define _SCOPE_H_

#include "pair.h"
#include "hashMap.h"

typedef struct Func Func;
typedef struct Variable Variable;

typedef struct Scope {
    /* Template is generated by object
     * declaration, new object will be
     * generated by copy from a specific
     * template.
     *
     * hMap<String, Object>*/
    hashMap *template;
    /* Map<ident, function> */
    hashMap *functions;
    /* Map<ident, primitive> */
    hashMap *primitives;
    /* Map<ident, object> */
    hashMap *objects;

    /* Reference to outer scope */
    struct Scope *outer;
} Scope;

/* Member functions implement as macros */
//#define scopeGetFunc(s, f) (hashMapSearch(s->functions, (void *)f))
//#define scopeGetPrimitive(s, p) (hashMapSearch(s->primitives, (void *)p))
//#define scopeGetObject(s, o) (hashMapSearch(s->objects, (void *)o))

#define isFuncExists(s, f) (scopeGetFunc(s,f) != null)
#define isPrimitiveExists(s, p) (scopeGetPrimitive(s, p) != null)
#define isObjectExists(s, o) (scopeGetObject(s, o) != null)

/* Prototypes */
Scope * scopeGenerate();
Scope * subScopeGenerate(Scope *);
void scopeRelease(Scope *);

Func * scopeGetFunc(Scope *, char *);
Variable * scopeGetPrimitive(Scope *, char *);
Variable * scopeGetObject(Scope *, char *);

/* pair<identifier, Func> */
_Status_t scopeNewFunc(Scope *, pair *);
/* pair<identifier, Primitive> */
_Status_t scopeNewPrimitive(Scope *, pair *);
/* pair<identifier, Object> */
_Status_t scopeNewObject(Scope *, pair *);

#ifdef _AST_TREE_TESTING_

void scopeTest(void **state);

#endif /* _AST_TREE_TESTING_ */

#endif /* _SCOPE_H_ */
