%union {
    char *str;
    int integer;
}

%token IMPORT
%token OBJECT
%token BELONG

%token MACHINE_OPERATIONS
%token ASSIGNMENT

%token COMMA COLON SEMICOLON DOT
%token OPEN_PAREN CLOSE_PAREN OPEN_SQUARE_BRACKET CLOSE_SQUARE_BRACKET
%token OPEN_CURVE_BRACKET CLOSE_CURVE_BRACKET

%token INT
%token STR

%token <str> IDENTIFIER
%token <integer> NUM

%code top { }

%%

PROGRAM :
    STATEMENTS;

STATEMENTS :
    STATEMENT STATEMENTS;

STATEMENT :
    IF_STATEMENT
    | RETURN_STATEMENT
    | VAR_DECL_STATEMENT
    | FUNC_DECL_STATEMENT
    | EXPRESSION_STATEMENT

/* Dangling else here should rewrite this to unambigurity */
IF_STATEMENT :
    IF OPEN_PAREN EXPRESSION CLOSE_PAREN BLOCK
    | IF OPEN_PAREN EXPRESSION CLOSE_PAREN BLOCK ELSE BLOCK;

RETURN_STATEMENT :
    RETURN EXPRESSION SEMICOLON;

VAR_DECL_STATEMENT :
    TYPE VAR_DECL_LIST SEMICOLON;

VAR_DECL_LIST :
    VAR_DECL COMMA VAR_DECL_LIST
    | VAR_DECL;

VAR_DECL :
    IDENTIFIER
    | ASSIGNMENT_STATEMENT;

FUNC_DECL_STATEMENT :
    TYPE IDENTIFIER OPEN_PAREN ARGUMENT_LIST CLOSE_PAREN SEMICOLON;

EXPRESSION_STATEMENT :
    EXPRESSION SEMICOLON;

EXPRESSION :
    OPEN_PAREN EXPRESSION CLOSE_PAREN
    | ARITHMETIC_EXPRESSION
    | ORDER_EXPRESSION
    | MEMBER_SELECTION_EXPRESSION
    | FUNCTION_CALL_EXPRESSION
    | ASSIGNMENT_EXPRESSION
    | CONSTANT
    | IDENTIFIER;

ARITHMETIC_EXPRESSION :
    PLUS_EXPRESSION
    | MINUS_EXPRESSION
    | MUL_EXPRESSION
    | DIV_EXPRESSION;

PLUS_EXPRESSION :
    EXPRESSION PLUS EXPRESSION;

MINUS_EXPRESSION :
    EXPRESSION MINUS EXPRESSION;

MUL_EXPRESSION :
    EXPRESSION MUL EXPRESSION;

DIV_EXPRESSION :
    EXPRESSION DIV EXPRESSION;

ORDER_EXPRESSION :
    LESS_THAN_EXPRESSION
    | GREATER_THAN_EXPRESSION
    | EQUAL_EXPRESSION
    | LESS_OR_EQUAL_EXPRESSION
    | GREATER_OR_EQUAL_EXPRESSION
    | NOT_EQUAL_EXPRESSION;

LESS_THAN_EXPRESSION :
    EXPRESSION LESS_THAN EXPRESSION;

GREATER_THAN_EXPRESSION :
    EXPRESSION GREATER_THAN EXPRESSION;

EQUAL_EXPRESSION :
    EXPRESSION EQUAL EXPRESSION;

LESS_OR_EQUAL_EXPRESSION :
    EXPRESSION LESS_OR_EQUAL EXPRESSION;

GREATER_OR_EQUAL_EXPRESSION :
    EXPRESSION GREATER_OR_EQUAL EXPRESSION;

NOT_EQUAL_EXPRESSION :
    EXPRESSION NOT_EQUAL EXPRESSION;

MEMBER_SELECTION_EXPRESSION :
    EXPRESSION DOT EXPRESSION MEMBER_SELECTION_EXPRESSION
    | DOT EXPRESSION MEMBER_SELECTION_EXPRESSION
    | /* empty */;

FUNCTION_CALL_EXPRESSION :
    IDENTIFIER OPEN_PAREN ARGUMENT_LIST CLOSE_PAREN ;

ARGUMENT_LIST :
    EXPRESSION
    | EXPRESSION COMMA ARGUMENT_LIST;

ASSIGNMENT_EXPRESSION :
    EXPRESSION ASSIGNMENT EXPRESSION;

BLOCK :
    STATEMENTS
    | STATEMENT

CONSTANT : NUM | STR_LITERAL;

TYPE :
    INT | STR | MACHINE_OPERATIONS;

%%