%union {
    char *str;
    int integer;
}

%token IMPORT FROM
%token RETURN
%token OBJECT
%token BELONG

%token MACHINE_OPERATIONS
%token ASSIGNMENT

%token IF ELSE

%token EQUAL LESS_THAN GREATER_THAN LESS_OR_EQUAL GREATER_OR_EQUAL NOT_EQUAL

%token COMMA COLON SEMICOLON DOT
%token OPEN_PAREN CLOSE_PAREN OPEN_SQUARE_BRACKET CLOSE_SQUARE_BRACKET
%token OPEN_CURVE_BRACKET CLOSE_CURVE_BRACKET

%token INT
%token STR

%token PLUS MINUS MUL DIV

%token <str> IDENTIFIER
%token <integer> NUM
%token <str> STR_LITERAL

%code top { }

%%

PROGRAM :
    STATEMENTS;

STATEMENTS :
    STATEMENT STATEMENTS
    | /* empty */;

STATEMENT :
    IF_STATEMENT
    | OBJECT_DECL_STATEMENT
    | IMPORT_STATEMENT
    | RETURN_STATEMENT
    | VAR_DECL_STATEMENT
    | FUNC_DECL_STATEMENT
    | EXPRESSION_STATEMENT;

/* Dangling else here should rewrite this to unambigurity */
IF_STATEMENT :
    IF OPEN_PAREN EXPRESSION CLOSE_PAREN BLOCK
    | IF OPEN_PAREN EXPRESSION CLOSE_PAREN BLOCK ELSE BLOCK;

OBJECT_DECL_STATEMENT :
    OBJECT IDENTIFIER OBJECT_INHERITENCE OPEN_CURVE_BRACKET OBJECT_DEF CLOSE_CURVE_BRACKET SEMICOLON;
OBJECT_INHERITENCE:
    BELONG IDENTIFIER
OBJECT_DEF :
    /* Use to set value within parent */
    IDENTIFIER BELONG IDENTIFIER ASSIGNMENT EXPRESSION SEMICOLON OBJECT_DEF
    /* Define a new member for the a new object */
    | TYPE IDENTIFIER SEMICOLON OBJECT_DEF
    | /* empty */;

IMPORT_STATEMENT :
    IMPORT IMPORT_LIST FROM IDENTIFIER
IMPORT_LIST :
    IDENTIFIER IMPORT_LIST
    | COMMA IDENTIFIER IMPORT_LIST
    | /* empty */

RETURN_STATEMENT :
    RETURN EXPRESSION SEMICOLON;

VAR_DECL_STATEMENT :
    TYPE VAR_DECL_LIST SEMICOLON;
VAR_DECL_LIST :
    VAR_DECL COMMA VAR_DECL_LIST
    | VAR_DECL;
VAR_DECL :
    IDENTIFIER
    | ASSIGNMENT_EXPRESSION;

FUNC_DECL_STATEMENT :
    TYPE IDENTIFIER OPEN_PAREN ARGUMENT_LIST CLOSE_PAREN SEMICOLON;

EXPRESSION_STATEMENT :
    EXPRESSION SEMICOLON;

TYPE :
    INT
    | STR
    | MACHINE_OPERATIONS;

EXPRESSION :
    OPEN_PAREN EXPRESSION CLOSE_PAREN
    | ARITHMETIC_EXPRESSION
    | ORDER_EXPRESSION
    | MEMBER_SELECTION_EXPRESSION
    | FUNCTION_CALL_EXPRESSION
    | ASSIGNMENT_EXPRESSION
    | CONSTANT
    | IDENTIFIER;

ARITHMETIC_EXPRESSION :
    PLUS_EXPRESSION
    | MINUS_EXPRESSION
    | MUL_EXPRESSION
    | DIV_EXPRESSION;

PLUS_EXPRESSION :
    EXPRESSION PLUS EXPRESSION;

MINUS_EXPRESSION :
    EXPRESSION MINUS EXPRESSION;

MUL_EXPRESSION :
    EXPRESSION MUL EXPRESSION;

DIV_EXPRESSION :
    EXPRESSION DIV EXPRESSION;

ORDER_EXPRESSION :
    LESS_THAN_EXPRESSION
    | GREATER_THAN_EXPRESSION
    | EQUAL_EXPRESSION
    | LESS_OR_EQUAL_EXPRESSION
    | GREATER_OR_EQUAL_EXPRESSION
    | NOT_EQUAL_EXPRESSION;

LESS_THAN_EXPRESSION :
    EXPRESSION LESS_THAN EXPRESSION;

GREATER_THAN_EXPRESSION :
    EXPRESSION GREATER_THAN EXPRESSION;

EQUAL_EXPRESSION :
    EXPRESSION EQUAL EXPRESSION;

LESS_OR_EQUAL_EXPRESSION :
    EXPRESSION LESS_OR_EQUAL EXPRESSION;

GREATER_OR_EQUAL_EXPRESSION :
    EXPRESSION GREATER_OR_EQUAL EXPRESSION;

NOT_EQUAL_EXPRESSION :
    EXPRESSION NOT_EQUAL EXPRESSION;

MEMBER_SELECTION_EXPRESSION :
    EXPRESSION MEMBER_SELECTION_EXPRESSION
    | DOT IDENTIFIER MEMBER_SELECTION_EXPRESSION;


FUNCTION_CALL_EXPRESSION :
    IDENTIFIER OPEN_PAREN ARGUMENT_LIST CLOSE_PAREN ;

ARGUMENT_LIST :
    EXPRESSION
    | EXPRESSION COMMA ARGUMENT_LIST;

ASSIGNMENT_EXPRESSION :
    EXPRESSION ASSIGNMENT EXPRESSION;

BLOCK :
    OPEN_CURVE_BRACKET STATEMENTS CLOSE_CURVE_BRACKET
    | STATEMENT;

CONSTANT : NUM | STR_LITERAL;

%%
